---
name: Verification

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-dist:
    name: Build font
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-dependencies
      - name: Lint glyph SVG files
        run: |
          python3 scripts/glyphclean.py glyphs/
          git diff --numstat --exit-code
      - name: Build dist
        run: python3 scripts/distbuild.py 0.0.0
      - name: Archive dist
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: dist
  check-file-types:
    name: Check file types
    needs: build-dist
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Unzip
        run: unzip dist/saltcandy123font.zip -d dist/unzipped
      - name: Show files
        run: |
          find dist -type f -exec ls -alh {} +
          find dist -type f -exec xargs file {} +
      - name: Check file types
        run: |
          cd dist/unzipped
          file saltcandy123font-Regular.ttf | grep "TrueType Font data,"
          file saltcandy123font-Regular.woff | grep "Web Open Font Format,"
  run-font-bakery:
    name: Check with Font Bakery
    needs: build-dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Unzip
        run: unzip dist/saltcandy123font.zip -d /tmp/saltcandy123font
      - name: Install Font Bakery
        run: python3 -m pip install fontbakery
      - name: Run Font Bakery
        run: |
          fontbakery check-universal \
            --ghmarkdown "${GITHUB_STEP_SUMMARY}" \
            -x com.google.fonts/check/monospace \
            /tmp/saltcandy123font/saltcandy123font-Regular.ttf
  run-super-linter:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*/glyphs/.*
